version: "3.9"

services:
  # Frontend project running on port 3000
  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
      dockerignore: .dockerignore
    ports:
      - "3000:3000"
    volumes:
      - ./portfolio-frontend:/app
    networks:
      - portfolio-network

  # Backend project running on port 8000
  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
      dockerignore: .dockerignore
    env_file:
      - ./portfolio-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db  # Ensures db service is started before backend
  db:
    image: mysql:8.0  
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./portfolio-backend:/var/www/html
    ports:
      - "3306:3306"
    networks:
      - portfolio-network

# Defines volumes for persisting data
volumes:
  dbdata:

# Defines network for service communication
networks:
  portfolio-network:
