version: "3.9"

services:
  portfolio-frontend:
    build:
      context: ./portfolio-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./portfolio-frontend:/app
    networks:
      - portfolio-network

  portfolio-backend:
    build:
      context: ./portfolio-backend
      dockerfile: Dockerfile
    env_file:
      - ./portfolio-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - portfolio-network

  db:
    image: mysql:8.0
    env_file:
      - ./portfolio-backend/.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - portfolio-network

volumes:
  dbdata:

networks:
  portfolio-network:
