name: portfolio

on:
 push:
   branches:
     -main
 pull_request:
   branches:
     -main
 workflow_dispatch:

  # Allows you to run this multiple os
jobs:
  frontend:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ./portfolio-frontend
    steps:

     # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
        # Step 2 Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio-frontend
        
        # Step 3: Run the build script
      - name: Run build 
        run: npm run build

  backend:
    runs-on: ${{ matrix.os }}
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ./portfolio-backend
    steps:

     # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        
        # Step 2 copy .env
      - name: Copy.env
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi
       # Step 3 Install PHP and dependencies os
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
 

       # step 4 install dependencies
      - name: Install composer dependencies
        run: composer install -n --prefer-dist
      
        # step 5 geneate key
      - name: Generate key
        run: php artisan key:generate
      
       # step 6 create database
      - name: create database
        run: |
             mkdir -p database
             touch database/database.mysql  

        # step 7 migrations
      - name: Run migrations
        run: php artisan migrate --seed

        #step 8 storage link
      - name: Storage link
        run: php artisan storage:link

        #step 9 permission
      - name: Permission
        run: chmod -R 777 storage bootstrap/cache

      # Step 10 run tests
      - name: Run tests
        run: php artisan test



